
import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";



const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["thai"],
  weight:["100","200","300","400","500","600","700","800","900"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable}  antialiased`}
      >

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        {children}
        <ToastContainer
        position="top-center"
        autoClose={2000}
        toastClassName="text-sm md:text-base rounded-lg px-4 text-center"
       
      />

      </body>
    </html>
  );
}
